project_id: "YOUR_PROJECT_ID"
folder_id: "YOUR_FOLDER_ID"
assignee: YOUR_USER_ID
configuration_name: "Chrome on Windows"
test_url: "YOUR_DEPLOYED_APP_URL"
scenario_limit: 3
test_cases_per_scenario: 5
